/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.interfacegraficajava;

import javax.swing.JOptionPane;

/**
 *
 * @author renan
 */
public class Tela extends javax.swing.JFrame {

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        tabbedLogin = new javax.swing.JPanel();
        panelLogin = new javax.swing.JPanel();
        labelTitulo = new javax.swing.JLabel();
        textFieldUsuario = new javax.swing.JTextField();
        textFieldSenha = new javax.swing.JTextField();
        checkBoxPermanecerConectado = new javax.swing.JCheckBox();
        buttonLogin = new javax.swing.JButton();
        buttonEsqueciSenha = new javax.swing.JButton();
        labelCriarNovaConta = new javax.swing.JLabel();
        tabbedCriarConta = new javax.swing.JPanel();
        panelCriarConta = new javax.swing.JPanel();
        textFieldNome = new javax.swing.JTextField();
        textFieldCriarUsuario = new javax.swing.JTextField();
        textFieldDefinirSenha = new javax.swing.JTextField();
        textFieldRepetirSenha = new javax.swing.JTextField();
        buttonCriarConta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 51, 153));

        jTabbedPane1.setBackground(new java.awt.Color(0, 0, 102));
        jTabbedPane1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setAutoscrolls(true);
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        tabbedLogin.setBackground(new java.awt.Color(0, 0, 153));
        tabbedLogin.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelLogin.setBackground(java.awt.Color.white);

        labelTitulo.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setIcon(new javax.swing.ImageIcon("D:\\Downloads\\imagem-do-usuario-com-fundo-preto (1).png")); // NOI18N
        labelTitulo.setText("Login");

        textFieldUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuário", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        textFieldSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        checkBoxPermanecerConectado.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        checkBoxPermanecerConectado.setText("Permanecer conectado");
        checkBoxPermanecerConectado.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        checkBoxPermanecerConectado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxPermanecerConectadoActionPerformed(evt);
            }
        });

        buttonLogin.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonLogin.setText("Login");
        buttonLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonLoginMouseClicked(evt);
            }
        });

        buttonEsqueciSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonEsqueciSenha.setText("Esqueci minha senha");

        javax.swing.GroupLayout panelLoginLayout = new javax.swing.GroupLayout(panelLogin);
        panelLogin.setLayout(panelLoginLayout);
        panelLoginLayout.setHorizontalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldUsuario)
                    .addComponent(textFieldSenha)
                    .addComponent(checkBoxPermanecerConectado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonEsqueciSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        panelLoginLayout.setVerticalGroup(
            panelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLoginLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(labelTitulo)
                .addGap(18, 18, 18)
                .addComponent(textFieldUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxPermanecerConectado, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(buttonEsqueciSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        labelCriarNovaConta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCriarNovaConta.setForeground(new java.awt.Color(255, 255, 255));
        labelCriarNovaConta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelCriarNovaConta.setText("Criar uma nova conta");

        javax.swing.GroupLayout tabbedLoginLayout = new javax.swing.GroupLayout(tabbedLogin);
        tabbedLogin.setLayout(tabbedLoginLayout);
        tabbedLoginLayout.setHorizontalGroup(
            tabbedLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabbedLoginLayout.createSequentialGroup()
                .addContainerGap(98, Short.MAX_VALUE)
                .addGroup(tabbedLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelCriarNovaConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        tabbedLoginLayout.setVerticalGroup(
            tabbedLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabbedLoginLayout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addComponent(panelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelCriarNovaConta)
                .addContainerGap(58, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", tabbedLogin);

        tabbedCriarConta.setBackground(new java.awt.Color(0, 0, 153));
        tabbedCriarConta.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelCriarConta.setBackground(java.awt.Color.white);

        textFieldNome.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldNome.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldNome.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome completo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        textFieldCriarUsuario.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldCriarUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldCriarUsuario.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Defina o nome de usuário", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        textFieldDefinirSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldDefinirSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldDefinirSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Defina a senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        textFieldRepetirSenha.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        textFieldRepetirSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        textFieldRepetirSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Repita a senha", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        buttonCriarConta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        buttonCriarConta.setText("Criar usuário");

        javax.swing.GroupLayout panelCriarContaLayout = new javax.swing.GroupLayout(panelCriarConta);
        panelCriarConta.setLayout(panelCriarContaLayout);
        panelCriarContaLayout.setHorizontalGroup(
            panelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriarContaLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addGroup(panelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(textFieldNome)
                    .addComponent(textFieldCriarUsuario)
                    .addComponent(textFieldDefinirSenha)
                    .addComponent(textFieldRepetirSenha)
                    .addComponent(buttonCriarConta, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelCriarContaLayout.setVerticalGroup(
            panelCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCriarContaLayout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(textFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldCriarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldDefinirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textFieldRepetirSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonCriarConta)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabbedCriarContaLayout = new javax.swing.GroupLayout(tabbedCriarConta);
        tabbedCriarConta.setLayout(tabbedCriarContaLayout);
        tabbedCriarContaLayout.setHorizontalGroup(
            tabbedCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabbedCriarContaLayout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(panelCriarConta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        tabbedCriarContaLayout.setVerticalGroup(
            tabbedCriarContaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabbedCriarContaLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(panelCriarConta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Criar conta", tabbedCriarConta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonLoginMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane,"Login efetuado com sucesso");
    }//GEN-LAST:event_buttonLoginMouseClicked

    private void checkBoxPermanecerConectadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxPermanecerConectadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkBoxPermanecerConectadoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCriarConta;
    private javax.swing.JButton buttonEsqueciSenha;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JCheckBox checkBoxPermanecerConectado;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelCriarNovaConta;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelCriarConta;
    private javax.swing.JPanel panelLogin;
    private javax.swing.JPanel tabbedCriarConta;
    private javax.swing.JPanel tabbedLogin;
    private javax.swing.JTextField textFieldCriarUsuario;
    private javax.swing.JTextField textFieldDefinirSenha;
    private javax.swing.JTextField textFieldNome;
    private javax.swing.JTextField textFieldRepetirSenha;
    private javax.swing.JTextField textFieldSenha;
    private javax.swing.JTextField textFieldUsuario;
    // End of variables declaration//GEN-END:variables
}
